### ISSUE TITLE
Пропал раздел bem-components

### ISSUE THREAD

**Issue by mrScrpt** [bem/bem-forum#103]
Здравствуйте. Пропала библиотека, по ссылке 404
https://ru.bem.info/platform/libs/bem-components/
Это специально убрали? Очень хотелось бы что бы вернули=)

**Comment by tadatuta** [comment]
Теперь она живет по новому адресу: https://ru.bem.info/libraries/classic/bem-components/

Навигацию и редиректы еще довозим.
