### ISSUE TITLE
 Поиск

### ISSUE THREAD

**Issue by APeltick** [bem/bem-forum#105]
Здравствуйте. Я видел issue по поиску, но у меня вопрос, есть ли стандартное поле для поиска по контексту и заголовкам статей? А то очень не удобно бегать по страницам или через google искать нужную информацию.

**Comment by tadatuta** [comment]
Чего-то более удобного, чем поиск по issues и https://yandex.ru/search/?text=site%3Aru.bem.info%2Fforum%20bem-xjst пока, к сожалению, нет :(
